language: go
go:
  - "1.80"

branches:
  only:
    - master

cache:
  directories:
    - themes

before_install:
- git config --global user.name "Shaloc"
- git config --global user.email "shalocn@outlook.com"

install:
  - go get github.com/gohugoio/hugo
  - if [ ! -d "themes/maupassant" ]; then git clone https://github.com/Shaloc/maupassant-kai themes/maupassant; fi

script:
  - hugo version
  - hugo config
  - hugo

after_success:
  - git clone -b master https://github.com/Shaloc/shaloc.github.io .deploy_git
  - cd .deploy_git
  - git checkout master
  - mv .git/ ../public/
  - cd ../public
  - git add .
  - git commit -m "Site updated: `date +"%Y-%m-%d %H:%M:%S"`"
  - git push origin master:master --force --quiet
