language: go
go: stable
repos:
  Shaloc/blog_hugo:
    endpoint: https://api.travis-ci.org/
addons:
  ssh_known_hosts:
  - github.com
  - gitee.com
  - shaloc.site
before_install:
- openssl aes-256-cbc -K $encrypted_3c7444b0f500_key -iv $encrypted_3c7444b0f500_iv
  -in travis.key.enc -out ~/.ssh/id_rsa -d
- git config --global user.name "Shaloc"
- git config --global user.email "shalocn@outlook.com"
install:
- go get github.com/gohugoio/hugo
- if [ ! -d "themes/maupassant" ]; then git clone https://github.com/Shaloc/maupassant-kai
  themes/maupassant; fi
script:
- hugo version
- hugo config
- hugo
after_success:
- .travis/deploy.sh
