language: go
go: stable
repos:
  Shaloc/blog_hugo:
    endpoint: https://api.travis-ci.org/
addons:
  ssh_known_hosts:
  - github.com
before_install:
- openssl aes-256-cbc -K $encrypted_3c7444b0f500_key -iv $encrypted_3c7444b0f500_iv
  -in ./.travis/get-favicon.enc -out ./.travis/get-favicon -d
- openssl aes-256-cbc -K $encrypted_016890f54c1f_key -iv $encrypted_016890f54c1f_iv
  -in ./.travis/travis.key.enc -out ~/.ssh/id_rsa -d
- ./.travis/get-favicon.sh
- chmod 400 ~/.ssh/id_rsa
- git config --global user.name "Shaloc"
- git config --global user.email "shalocn@outlook.com"
install:
- cd ..
- wget https://github.com/gohugoio/hugo/releases/download/v0.67.1/hugo_0.67.1_Linux-64bit.deb
- sudo dpkg -i ./hugo_0.67.1_Linux-64bit.deb
- sudo apt-get install -f
- cd blog_hugo
script:
- hugo version
- hugo
after_success:
- .travis/deploy.sh
