language: go
go: stable

before_install:
- git config --global user.name "Shaloc"
- git config --global user.email "shalocn@outlook.com"

install:
- go get github.com/gohugoio/hugo
- if [ ! -d "themes/maupassant" ]; then git clone https://github.com/Shaloc/maupassant-kai themes/maupassant; fi

script:
- hugo version
- hugo config
- hugo

after_success:
- .travis/deploy.sh
