baseURL = "https://shaloc.site"
languageCode = "en-us"
title = "Fagus!"
subtitle = "洛克的生活研究所"
theme = "maupassant"

## 是否禁止URL Path转小写
disablePathToLower = true

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

## googleAnalytics
googleAnalytics = "UA-132327203-1"

[author]
name = "Shaloc"

[params]
author = "Shaloc"
subtitle = "洛克的自留研究所"
busuanzi = true

[params.utteranc]
    enable = true
    repo = "Shaloc/review"
    issueTerm = "pathname"
    theme = "github-light"


[menu]
[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 3

[[params.links]]
  title = "sm.ms"
  name = "土豪兽兽建的图床"
  url = "https://sm.ms/"

[[params.links]]
  title = "liu-lingfei"
  name = "一个学弟的博客"
  url = "https://liu-lingfei.github.io/"


