baseURL = "https://gblog.shaloc.site"
languageCode = "en-us"
title = "大可爱和巨可爱"
subtitle = "想你，脑袋里都是你"
theme = "maupassant"

## 是否禁止URL Path转小写
disablePathToLower = true

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

## googleAnalytics
googleAnalytics = "UA-132327203-1"

[author]
name = "Shaloc"


[params]
author = "Shaloc"
subtitle = "想你，脑袋里都是你"
busuanzi = true

[params.utteranc]
    enable = true
    repo = "Shaloc/review"
    issueTerm = "pathname"
    theme = "github-light"

[markup]
    [markup.highlight]
        lineNos = false
        style = "github"

[menu]
[[menu.main]]
  identifier = "lover"
  name = "大可爱"
  url = "/lover/"
  weight = 2
[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 3
[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 4

[[params.links]]
  title = "sm.ms"
  name = "土豪兽兽建的图床"
  url = "https://sm.ms/"

[[params.links]]
  title = "liu-lingfei"
  name = "一个学弟的博客"
  url = "https://liu-lingfei.github.io/"


